// Code generated by ent, DO NOT EDIT.

package tenantuserview

import (
	"good-todo-go/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldContainsFold(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldEQ(FieldTenantID, v))
}

// TenantName applies equality check predicate on the "tenant_name" field. It's identical to TenantNameEQ.
func TenantName(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldEQ(FieldTenantName, v))
}

// TenantSlug applies equality check predicate on the "tenant_slug" field. It's identical to TenantSlugEQ.
func TenantSlug(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldEQ(FieldTenantSlug, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldEQ(FieldEmail, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldEQ(FieldName, v))
}

// Role applies equality check predicate on the "role" field. It's identical to RoleEQ.
func Role(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldEQ(FieldRole, v))
}

// EmailVerified applies equality check predicate on the "email_verified" field. It's identical to EmailVerifiedEQ.
func EmailVerified(v bool) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldEQ(FieldEmailVerified, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldEQ(FieldUpdatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldContainsFold(FieldTenantID, v))
}

// TenantNameEQ applies the EQ predicate on the "tenant_name" field.
func TenantNameEQ(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldEQ(FieldTenantName, v))
}

// TenantNameNEQ applies the NEQ predicate on the "tenant_name" field.
func TenantNameNEQ(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldNEQ(FieldTenantName, v))
}

// TenantNameIn applies the In predicate on the "tenant_name" field.
func TenantNameIn(vs ...string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldIn(FieldTenantName, vs...))
}

// TenantNameNotIn applies the NotIn predicate on the "tenant_name" field.
func TenantNameNotIn(vs ...string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldNotIn(FieldTenantName, vs...))
}

// TenantNameGT applies the GT predicate on the "tenant_name" field.
func TenantNameGT(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldGT(FieldTenantName, v))
}

// TenantNameGTE applies the GTE predicate on the "tenant_name" field.
func TenantNameGTE(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldGTE(FieldTenantName, v))
}

// TenantNameLT applies the LT predicate on the "tenant_name" field.
func TenantNameLT(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldLT(FieldTenantName, v))
}

// TenantNameLTE applies the LTE predicate on the "tenant_name" field.
func TenantNameLTE(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldLTE(FieldTenantName, v))
}

// TenantNameContains applies the Contains predicate on the "tenant_name" field.
func TenantNameContains(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldContains(FieldTenantName, v))
}

// TenantNameHasPrefix applies the HasPrefix predicate on the "tenant_name" field.
func TenantNameHasPrefix(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldHasPrefix(FieldTenantName, v))
}

// TenantNameHasSuffix applies the HasSuffix predicate on the "tenant_name" field.
func TenantNameHasSuffix(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldHasSuffix(FieldTenantName, v))
}

// TenantNameEqualFold applies the EqualFold predicate on the "tenant_name" field.
func TenantNameEqualFold(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldEqualFold(FieldTenantName, v))
}

// TenantNameContainsFold applies the ContainsFold predicate on the "tenant_name" field.
func TenantNameContainsFold(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldContainsFold(FieldTenantName, v))
}

// TenantSlugEQ applies the EQ predicate on the "tenant_slug" field.
func TenantSlugEQ(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldEQ(FieldTenantSlug, v))
}

// TenantSlugNEQ applies the NEQ predicate on the "tenant_slug" field.
func TenantSlugNEQ(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldNEQ(FieldTenantSlug, v))
}

// TenantSlugIn applies the In predicate on the "tenant_slug" field.
func TenantSlugIn(vs ...string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldIn(FieldTenantSlug, vs...))
}

// TenantSlugNotIn applies the NotIn predicate on the "tenant_slug" field.
func TenantSlugNotIn(vs ...string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldNotIn(FieldTenantSlug, vs...))
}

// TenantSlugGT applies the GT predicate on the "tenant_slug" field.
func TenantSlugGT(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldGT(FieldTenantSlug, v))
}

// TenantSlugGTE applies the GTE predicate on the "tenant_slug" field.
func TenantSlugGTE(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldGTE(FieldTenantSlug, v))
}

// TenantSlugLT applies the LT predicate on the "tenant_slug" field.
func TenantSlugLT(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldLT(FieldTenantSlug, v))
}

// TenantSlugLTE applies the LTE predicate on the "tenant_slug" field.
func TenantSlugLTE(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldLTE(FieldTenantSlug, v))
}

// TenantSlugContains applies the Contains predicate on the "tenant_slug" field.
func TenantSlugContains(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldContains(FieldTenantSlug, v))
}

// TenantSlugHasPrefix applies the HasPrefix predicate on the "tenant_slug" field.
func TenantSlugHasPrefix(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldHasPrefix(FieldTenantSlug, v))
}

// TenantSlugHasSuffix applies the HasSuffix predicate on the "tenant_slug" field.
func TenantSlugHasSuffix(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldHasSuffix(FieldTenantSlug, v))
}

// TenantSlugEqualFold applies the EqualFold predicate on the "tenant_slug" field.
func TenantSlugEqualFold(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldEqualFold(FieldTenantSlug, v))
}

// TenantSlugContainsFold applies the ContainsFold predicate on the "tenant_slug" field.
func TenantSlugContainsFold(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldContainsFold(FieldTenantSlug, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldContainsFold(FieldEmail, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldContainsFold(FieldName, v))
}

// RoleEQ applies the EQ predicate on the "role" field.
func RoleEQ(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldEQ(FieldRole, v))
}

// RoleNEQ applies the NEQ predicate on the "role" field.
func RoleNEQ(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldNEQ(FieldRole, v))
}

// RoleIn applies the In predicate on the "role" field.
func RoleIn(vs ...string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldIn(FieldRole, vs...))
}

// RoleNotIn applies the NotIn predicate on the "role" field.
func RoleNotIn(vs ...string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldNotIn(FieldRole, vs...))
}

// RoleGT applies the GT predicate on the "role" field.
func RoleGT(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldGT(FieldRole, v))
}

// RoleGTE applies the GTE predicate on the "role" field.
func RoleGTE(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldGTE(FieldRole, v))
}

// RoleLT applies the LT predicate on the "role" field.
func RoleLT(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldLT(FieldRole, v))
}

// RoleLTE applies the LTE predicate on the "role" field.
func RoleLTE(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldLTE(FieldRole, v))
}

// RoleContains applies the Contains predicate on the "role" field.
func RoleContains(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldContains(FieldRole, v))
}

// RoleHasPrefix applies the HasPrefix predicate on the "role" field.
func RoleHasPrefix(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldHasPrefix(FieldRole, v))
}

// RoleHasSuffix applies the HasSuffix predicate on the "role" field.
func RoleHasSuffix(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldHasSuffix(FieldRole, v))
}

// RoleEqualFold applies the EqualFold predicate on the "role" field.
func RoleEqualFold(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldEqualFold(FieldRole, v))
}

// RoleContainsFold applies the ContainsFold predicate on the "role" field.
func RoleContainsFold(v string) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldContainsFold(FieldRole, v))
}

// EmailVerifiedEQ applies the EQ predicate on the "email_verified" field.
func EmailVerifiedEQ(v bool) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldEQ(FieldEmailVerified, v))
}

// EmailVerifiedNEQ applies the NEQ predicate on the "email_verified" field.
func EmailVerifiedNEQ(v bool) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldNEQ(FieldEmailVerified, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TenantUserView {
	return predicate.TenantUserView(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TenantUserView) predicate.TenantUserView {
	return predicate.TenantUserView(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TenantUserView) predicate.TenantUserView {
	return predicate.TenantUserView(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TenantUserView) predicate.TenantUserView {
	return predicate.TenantUserView(sql.NotPredicates(p))
}
