extends:
  - recommended

apis:
  public:
    root: ./openapi/openapi-public.yaml
  admin:
    root: ./openapi/openapi-admin.yaml

rules:
  no-unused-components: warn
  operation-operationId: error
  tag-description: off
  security-defined: off
  info-license: off
  no-server-example.com: off
  operation-4xx-response: off
