// Code generated by MockGen. DO NOT EDIT.
// Source: auth.go
//
// Generated by this command:
//
//	mockgen -source=auth.go -destination=mock/auth.go -package=mock_usecase
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	input "good-todo-go/internal/usecase/input"
	output "good-todo-go/internal/usecase/output"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIAuthInteractor is a mock of IAuthInteractor interface.
type MockIAuthInteractor struct {
	ctrl     *gomock.Controller
	recorder *MockIAuthInteractorMockRecorder
	isgomock struct{}
}

// MockIAuthInteractorMockRecorder is the mock recorder for MockIAuthInteractor.
type MockIAuthInteractorMockRecorder struct {
	mock *MockIAuthInteractor
}

// NewMockIAuthInteractor creates a new mock instance.
func NewMockIAuthInteractor(ctrl *gomock.Controller) *MockIAuthInteractor {
	mock := &MockIAuthInteractor{ctrl: ctrl}
	mock.recorder = &MockIAuthInteractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAuthInteractor) EXPECT() *MockIAuthInteractorMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockIAuthInteractor) Login(ctx context.Context, in *input.LoginInput) (*output.AuthOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, in)
	ret0, _ := ret[0].(*output.AuthOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockIAuthInteractorMockRecorder) Login(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockIAuthInteractor)(nil).Login), ctx, in)
}

// RefreshToken mocks base method.
func (m *MockIAuthInteractor) RefreshToken(ctx context.Context, in *input.RefreshTokenInput) (*output.AuthOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", ctx, in)
	ret0, _ := ret[0].(*output.AuthOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockIAuthInteractorMockRecorder) RefreshToken(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockIAuthInteractor)(nil).RefreshToken), ctx, in)
}

// Register mocks base method.
func (m *MockIAuthInteractor) Register(ctx context.Context, in *input.RegisterInput) (*output.AuthOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, in)
	ret0, _ := ret[0].(*output.AuthOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockIAuthInteractorMockRecorder) Register(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockIAuthInteractor)(nil).Register), ctx, in)
}

// VerifyEmail mocks base method.
func (m *MockIAuthInteractor) VerifyEmail(ctx context.Context, in *input.VerifyEmailInput) (*output.VerifyEmailOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyEmail", ctx, in)
	ret0, _ := ret[0].(*output.VerifyEmailOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyEmail indicates an expected call of VerifyEmail.
func (mr *MockIAuthInteractorMockRecorder) VerifyEmail(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyEmail", reflect.TypeOf((*MockIAuthInteractor)(nil).VerifyEmail), ctx, in)
}
