// Code generated by MockGen. DO NOT EDIT.
// Source: todo.go
//
// Generated by this command:
//
//	mockgen -source=todo.go -destination=mock/todo.go -package=mock_usecase
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	input "good-todo-go/internal/usecase/input"
	output "good-todo-go/internal/usecase/output"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockITodoInteractor is a mock of ITodoInteractor interface.
type MockITodoInteractor struct {
	ctrl     *gomock.Controller
	recorder *MockITodoInteractorMockRecorder
	isgomock struct{}
}

// MockITodoInteractorMockRecorder is the mock recorder for MockITodoInteractor.
type MockITodoInteractorMockRecorder struct {
	mock *MockITodoInteractor
}

// NewMockITodoInteractor creates a new mock instance.
func NewMockITodoInteractor(ctrl *gomock.Controller) *MockITodoInteractor {
	mock := &MockITodoInteractor{ctrl: ctrl}
	mock.recorder = &MockITodoInteractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITodoInteractor) EXPECT() *MockITodoInteractorMockRecorder {
	return m.recorder
}

// CreateTodo mocks base method.
func (m *MockITodoInteractor) CreateTodo(ctx context.Context, in *input.CreateTodoInput) (*output.TodoOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTodo", ctx, in)
	ret0, _ := ret[0].(*output.TodoOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTodo indicates an expected call of CreateTodo.
func (mr *MockITodoInteractorMockRecorder) CreateTodo(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTodo", reflect.TypeOf((*MockITodoInteractor)(nil).CreateTodo), ctx, in)
}

// DeleteTodo mocks base method.
func (m *MockITodoInteractor) DeleteTodo(ctx context.Context, todoID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTodo", ctx, todoID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTodo indicates an expected call of DeleteTodo.
func (mr *MockITodoInteractorMockRecorder) DeleteTodo(ctx, todoID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTodo", reflect.TypeOf((*MockITodoInteractor)(nil).DeleteTodo), ctx, todoID, userID)
}

// GetPublicTodos mocks base method.
func (m *MockITodoInteractor) GetPublicTodos(ctx context.Context, in *input.GetPublicTodosInput) (*output.TodoListOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicTodos", ctx, in)
	ret0, _ := ret[0].(*output.TodoListOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicTodos indicates an expected call of GetPublicTodos.
func (mr *MockITodoInteractorMockRecorder) GetPublicTodos(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicTodos", reflect.TypeOf((*MockITodoInteractor)(nil).GetPublicTodos), ctx, in)
}

// GetTodo mocks base method.
func (m *MockITodoInteractor) GetTodo(ctx context.Context, todoID, userID string) (*output.TodoOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTodo", ctx, todoID, userID)
	ret0, _ := ret[0].(*output.TodoOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTodo indicates an expected call of GetTodo.
func (mr *MockITodoInteractorMockRecorder) GetTodo(ctx, todoID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTodo", reflect.TypeOf((*MockITodoInteractor)(nil).GetTodo), ctx, todoID, userID)
}

// GetTodos mocks base method.
func (m *MockITodoInteractor) GetTodos(ctx context.Context, in *input.GetTodosInput) (*output.TodoListOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTodos", ctx, in)
	ret0, _ := ret[0].(*output.TodoListOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTodos indicates an expected call of GetTodos.
func (mr *MockITodoInteractorMockRecorder) GetTodos(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTodos", reflect.TypeOf((*MockITodoInteractor)(nil).GetTodos), ctx, in)
}

// UpdateTodo mocks base method.
func (m *MockITodoInteractor) UpdateTodo(ctx context.Context, in *input.UpdateTodoInput) (*output.TodoOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTodo", ctx, in)
	ret0, _ := ret[0].(*output.TodoOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTodo indicates an expected call of UpdateTodo.
func (mr *MockITodoInteractorMockRecorder) UpdateTodo(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTodo", reflect.TypeOf((*MockITodoInteractor)(nil).UpdateTodo), ctx, in)
}
