// Code generated by MockGen. DO NOT EDIT.
// Source: user.go
//
// Generated by this command:
//
//	mockgen -source=user.go -destination=mock/user.go -package=mock_usecase
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	input "good-todo-go/internal/usecase/input"
	output "good-todo-go/internal/usecase/output"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIUserInteractor is a mock of IUserInteractor interface.
type MockIUserInteractor struct {
	ctrl     *gomock.Controller
	recorder *MockIUserInteractorMockRecorder
	isgomock struct{}
}

// MockIUserInteractorMockRecorder is the mock recorder for MockIUserInteractor.
type MockIUserInteractorMockRecorder struct {
	mock *MockIUserInteractor
}

// NewMockIUserInteractor creates a new mock instance.
func NewMockIUserInteractor(ctrl *gomock.Controller) *MockIUserInteractor {
	mock := &MockIUserInteractor{ctrl: ctrl}
	mock.recorder = &MockIUserInteractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUserInteractor) EXPECT() *MockIUserInteractorMockRecorder {
	return m.recorder
}

// GetMe mocks base method.
func (m *MockIUserInteractor) GetMe(ctx context.Context, userID string) (*output.UserOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMe", ctx, userID)
	ret0, _ := ret[0].(*output.UserOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMe indicates an expected call of GetMe.
func (mr *MockIUserInteractorMockRecorder) GetMe(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMe", reflect.TypeOf((*MockIUserInteractor)(nil).GetMe), ctx, userID)
}

// UpdateMe mocks base method.
func (m *MockIUserInteractor) UpdateMe(ctx context.Context, in *input.UpdateUserInput) (*output.UserOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMe", ctx, in)
	ret0, _ := ret[0].(*output.UserOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMe indicates an expected call of UpdateMe.
func (mr *MockIUserInteractorMockRecorder) UpdateMe(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMe", reflect.TypeOf((*MockIUserInteractor)(nil).UpdateMe), ctx, in)
}
