// Code generated by ent, DO NOT EDIT.

package ent

import (
	"good-todo-go/internal/ent/schema"
	"good-todo-go/internal/ent/tenant"
	"good-todo-go/internal/ent/tenanttodoview"
	"good-todo-go/internal/ent/tenantuserview"
	"good-todo-go/internal/ent/todo"
	"good-todo-go/internal/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	tenantFields := schema.Tenant{}.Fields()
	_ = tenantFields
	// tenantDescName is the schema descriptor for name field.
	tenantDescName := tenantFields[1].Descriptor()
	// tenant.NameValidator is a validator for the "name" field. It is called by the builders before save.
	tenant.NameValidator = tenantDescName.Validators[0].(func(string) error)
	// tenantDescSlug is the schema descriptor for slug field.
	tenantDescSlug := tenantFields[2].Descriptor()
	// tenant.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	tenant.SlugValidator = tenantDescSlug.Validators[0].(func(string) error)
	// tenantDescCreatedAt is the schema descriptor for created_at field.
	tenantDescCreatedAt := tenantFields[3].Descriptor()
	// tenant.DefaultCreatedAt holds the default value on creation for the created_at field.
	tenant.DefaultCreatedAt = tenantDescCreatedAt.Default.(func() time.Time)
	// tenantDescUpdatedAt is the schema descriptor for updated_at field.
	tenantDescUpdatedAt := tenantFields[4].Descriptor()
	// tenant.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tenant.DefaultUpdatedAt = tenantDescUpdatedAt.Default.(func() time.Time)
	// tenant.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tenant.UpdateDefaultUpdatedAt = tenantDescUpdatedAt.UpdateDefault.(func() time.Time)
	// tenantDescID is the schema descriptor for id field.
	tenantDescID := tenantFields[0].Descriptor()
	// tenant.IDValidator is a validator for the "id" field. It is called by the builders before save.
	tenant.IDValidator = tenantDescID.Validators[0].(func(string) error)
	tenanttodoviewFields := schema.TenantTodoView{}.Fields()
	_ = tenanttodoviewFields
	// tenanttodoviewDescCreatedAt is the schema descriptor for created_at field.
	tenanttodoviewDescCreatedAt := tenanttodoviewFields[10].Descriptor()
	// tenanttodoview.DefaultCreatedAt holds the default value on creation for the created_at field.
	tenanttodoview.DefaultCreatedAt = tenanttodoviewDescCreatedAt.Default.(func() time.Time)
	// tenanttodoviewDescUpdatedAt is the schema descriptor for updated_at field.
	tenanttodoviewDescUpdatedAt := tenanttodoviewFields[11].Descriptor()
	// tenanttodoview.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tenanttodoview.DefaultUpdatedAt = tenanttodoviewDescUpdatedAt.Default.(func() time.Time)
	tenantuserviewFields := schema.TenantUserView{}.Fields()
	_ = tenantuserviewFields
	// tenantuserviewDescCreatedAt is the schema descriptor for created_at field.
	tenantuserviewDescCreatedAt := tenantuserviewFields[8].Descriptor()
	// tenantuserview.DefaultCreatedAt holds the default value on creation for the created_at field.
	tenantuserview.DefaultCreatedAt = tenantuserviewDescCreatedAt.Default.(func() time.Time)
	// tenantuserviewDescUpdatedAt is the schema descriptor for updated_at field.
	tenantuserviewDescUpdatedAt := tenantuserviewFields[9].Descriptor()
	// tenantuserview.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tenantuserview.DefaultUpdatedAt = tenantuserviewDescUpdatedAt.Default.(func() time.Time)
	todoFields := schema.Todo{}.Fields()
	_ = todoFields
	// todoDescTenantID is the schema descriptor for tenant_id field.
	todoDescTenantID := todoFields[1].Descriptor()
	// todo.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	todo.TenantIDValidator = todoDescTenantID.Validators[0].(func(string) error)
	// todoDescUserID is the schema descriptor for user_id field.
	todoDescUserID := todoFields[2].Descriptor()
	// todo.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	todo.UserIDValidator = todoDescUserID.Validators[0].(func(string) error)
	// todoDescTitle is the schema descriptor for title field.
	todoDescTitle := todoFields[3].Descriptor()
	// todo.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	todo.TitleValidator = todoDescTitle.Validators[0].(func(string) error)
	// todoDescDescription is the schema descriptor for description field.
	todoDescDescription := todoFields[4].Descriptor()
	// todo.DefaultDescription holds the default value on creation for the description field.
	todo.DefaultDescription = todoDescDescription.Default.(string)
	// todoDescCompleted is the schema descriptor for completed field.
	todoDescCompleted := todoFields[5].Descriptor()
	// todo.DefaultCompleted holds the default value on creation for the completed field.
	todo.DefaultCompleted = todoDescCompleted.Default.(bool)
	// todoDescCreatedAt is the schema descriptor for created_at field.
	todoDescCreatedAt := todoFields[8].Descriptor()
	// todo.DefaultCreatedAt holds the default value on creation for the created_at field.
	todo.DefaultCreatedAt = todoDescCreatedAt.Default.(func() time.Time)
	// todoDescUpdatedAt is the schema descriptor for updated_at field.
	todoDescUpdatedAt := todoFields[9].Descriptor()
	// todo.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	todo.DefaultUpdatedAt = todoDescUpdatedAt.Default.(func() time.Time)
	// todo.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	todo.UpdateDefaultUpdatedAt = todoDescUpdatedAt.UpdateDefault.(func() time.Time)
	// todoDescID is the schema descriptor for id field.
	todoDescID := todoFields[0].Descriptor()
	// todo.IDValidator is a validator for the "id" field. It is called by the builders before save.
	todo.IDValidator = todoDescID.Validators[0].(func(string) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescTenantID is the schema descriptor for tenant_id field.
	userDescTenantID := userFields[1].Descriptor()
	// user.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	user.TenantIDValidator = userDescTenantID.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[2].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[3].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[4].Descriptor()
	// user.DefaultName holds the default value on creation for the name field.
	user.DefaultName = userDescName.Default.(string)
	// userDescEmailVerified is the schema descriptor for email_verified field.
	userDescEmailVerified := userFields[6].Descriptor()
	// user.DefaultEmailVerified holds the default value on creation for the email_verified field.
	user.DefaultEmailVerified = userDescEmailVerified.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[9].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[10].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.IDValidator is a validator for the "id" field. It is called by the builders before save.
	user.IDValidator = userDescID.Validators[0].(func(string) error)
}
