// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"good-todo-go/internal/ent/predicate"
	"good-todo-go/internal/ent/tenantuserview"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TenantUserViewUpdate is the builder for updating TenantUserView entities.
type TenantUserViewUpdate struct {
	config
	hooks    []Hook
	mutation *TenantUserViewMutation
}

// Where appends a list predicates to the TenantUserViewUpdate builder.
func (_u *TenantUserViewUpdate) Where(ps ...predicate.TenantUserView) *TenantUserViewUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *TenantUserViewUpdate) SetTenantID(v string) *TenantUserViewUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *TenantUserViewUpdate) SetNillableTenantID(v *string) *TenantUserViewUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetTenantName sets the "tenant_name" field.
func (_u *TenantUserViewUpdate) SetTenantName(v string) *TenantUserViewUpdate {
	_u.mutation.SetTenantName(v)
	return _u
}

// SetNillableTenantName sets the "tenant_name" field if the given value is not nil.
func (_u *TenantUserViewUpdate) SetNillableTenantName(v *string) *TenantUserViewUpdate {
	if v != nil {
		_u.SetTenantName(*v)
	}
	return _u
}

// SetTenantSlug sets the "tenant_slug" field.
func (_u *TenantUserViewUpdate) SetTenantSlug(v string) *TenantUserViewUpdate {
	_u.mutation.SetTenantSlug(v)
	return _u
}

// SetNillableTenantSlug sets the "tenant_slug" field if the given value is not nil.
func (_u *TenantUserViewUpdate) SetNillableTenantSlug(v *string) *TenantUserViewUpdate {
	if v != nil {
		_u.SetTenantSlug(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *TenantUserViewUpdate) SetEmail(v string) *TenantUserViewUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *TenantUserViewUpdate) SetNillableEmail(v *string) *TenantUserViewUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *TenantUserViewUpdate) SetName(v string) *TenantUserViewUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TenantUserViewUpdate) SetNillableName(v *string) *TenantUserViewUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *TenantUserViewUpdate) SetRole(v string) *TenantUserViewUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *TenantUserViewUpdate) SetNillableRole(v *string) *TenantUserViewUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetEmailVerified sets the "email_verified" field.
func (_u *TenantUserViewUpdate) SetEmailVerified(v bool) *TenantUserViewUpdate {
	_u.mutation.SetEmailVerified(v)
	return _u
}

// SetNillableEmailVerified sets the "email_verified" field if the given value is not nil.
func (_u *TenantUserViewUpdate) SetNillableEmailVerified(v *bool) *TenantUserViewUpdate {
	if v != nil {
		_u.SetEmailVerified(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TenantUserViewUpdate) SetCreatedAt(v time.Time) *TenantUserViewUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TenantUserViewUpdate) SetNillableCreatedAt(v *time.Time) *TenantUserViewUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TenantUserViewUpdate) SetUpdatedAt(v time.Time) *TenantUserViewUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *TenantUserViewUpdate) SetNillableUpdatedAt(v *time.Time) *TenantUserViewUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the TenantUserViewMutation object of the builder.
func (_u *TenantUserViewUpdate) Mutation() *TenantUserViewMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TenantUserViewUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantUserViewUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TenantUserViewUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantUserViewUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *TenantUserViewUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(tenantuserview.Table, tenantuserview.Columns, sqlgraph.NewFieldSpec(tenantuserview.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(tenantuserview.FieldTenantID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TenantName(); ok {
		_spec.SetField(tenantuserview.FieldTenantName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TenantSlug(); ok {
		_spec.SetField(tenantuserview.FieldTenantSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(tenantuserview.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tenantuserview.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(tenantuserview.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.EmailVerified(); ok {
		_spec.SetField(tenantuserview.FieldEmailVerified, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(tenantuserview.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tenantuserview.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenantuserview.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TenantUserViewUpdateOne is the builder for updating a single TenantUserView entity.
type TenantUserViewUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TenantUserViewMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *TenantUserViewUpdateOne) SetTenantID(v string) *TenantUserViewUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *TenantUserViewUpdateOne) SetNillableTenantID(v *string) *TenantUserViewUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetTenantName sets the "tenant_name" field.
func (_u *TenantUserViewUpdateOne) SetTenantName(v string) *TenantUserViewUpdateOne {
	_u.mutation.SetTenantName(v)
	return _u
}

// SetNillableTenantName sets the "tenant_name" field if the given value is not nil.
func (_u *TenantUserViewUpdateOne) SetNillableTenantName(v *string) *TenantUserViewUpdateOne {
	if v != nil {
		_u.SetTenantName(*v)
	}
	return _u
}

// SetTenantSlug sets the "tenant_slug" field.
func (_u *TenantUserViewUpdateOne) SetTenantSlug(v string) *TenantUserViewUpdateOne {
	_u.mutation.SetTenantSlug(v)
	return _u
}

// SetNillableTenantSlug sets the "tenant_slug" field if the given value is not nil.
func (_u *TenantUserViewUpdateOne) SetNillableTenantSlug(v *string) *TenantUserViewUpdateOne {
	if v != nil {
		_u.SetTenantSlug(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *TenantUserViewUpdateOne) SetEmail(v string) *TenantUserViewUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *TenantUserViewUpdateOne) SetNillableEmail(v *string) *TenantUserViewUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *TenantUserViewUpdateOne) SetName(v string) *TenantUserViewUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TenantUserViewUpdateOne) SetNillableName(v *string) *TenantUserViewUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *TenantUserViewUpdateOne) SetRole(v string) *TenantUserViewUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *TenantUserViewUpdateOne) SetNillableRole(v *string) *TenantUserViewUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetEmailVerified sets the "email_verified" field.
func (_u *TenantUserViewUpdateOne) SetEmailVerified(v bool) *TenantUserViewUpdateOne {
	_u.mutation.SetEmailVerified(v)
	return _u
}

// SetNillableEmailVerified sets the "email_verified" field if the given value is not nil.
func (_u *TenantUserViewUpdateOne) SetNillableEmailVerified(v *bool) *TenantUserViewUpdateOne {
	if v != nil {
		_u.SetEmailVerified(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TenantUserViewUpdateOne) SetCreatedAt(v time.Time) *TenantUserViewUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TenantUserViewUpdateOne) SetNillableCreatedAt(v *time.Time) *TenantUserViewUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TenantUserViewUpdateOne) SetUpdatedAt(v time.Time) *TenantUserViewUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *TenantUserViewUpdateOne) SetNillableUpdatedAt(v *time.Time) *TenantUserViewUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the TenantUserViewMutation object of the builder.
func (_u *TenantUserViewUpdateOne) Mutation() *TenantUserViewMutation {
	return _u.mutation
}

// Where appends a list predicates to the TenantUserViewUpdate builder.
func (_u *TenantUserViewUpdateOne) Where(ps ...predicate.TenantUserView) *TenantUserViewUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TenantUserViewUpdateOne) Select(field string, fields ...string) *TenantUserViewUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TenantUserView entity.
func (_u *TenantUserViewUpdateOne) Save(ctx context.Context) (*TenantUserView, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantUserViewUpdateOne) SaveX(ctx context.Context) *TenantUserView {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TenantUserViewUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantUserViewUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *TenantUserViewUpdateOne) sqlSave(ctx context.Context) (_node *TenantUserView, err error) {
	_spec := sqlgraph.NewUpdateSpec(tenantuserview.Table, tenantuserview.Columns, sqlgraph.NewFieldSpec(tenantuserview.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TenantUserView.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tenantuserview.FieldID)
		for _, f := range fields {
			if !tenantuserview.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tenantuserview.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(tenantuserview.FieldTenantID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TenantName(); ok {
		_spec.SetField(tenantuserview.FieldTenantName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TenantSlug(); ok {
		_spec.SetField(tenantuserview.FieldTenantSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(tenantuserview.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tenantuserview.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(tenantuserview.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.EmailVerified(); ok {
		_spec.SetField(tenantuserview.FieldEmailVerified, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(tenantuserview.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tenantuserview.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &TenantUserView{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenantuserview.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
