// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"good-todo-go/internal/ent/predicate"
	"good-todo-go/internal/ent/tenantuserview"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TenantUserViewDelete is the builder for deleting a TenantUserView entity.
type TenantUserViewDelete struct {
	config
	hooks    []Hook
	mutation *TenantUserViewMutation
}

// Where appends a list predicates to the TenantUserViewDelete builder.
func (_d *TenantUserViewDelete) Where(ps ...predicate.TenantUserView) *TenantUserViewDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TenantUserViewDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TenantUserViewDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TenantUserViewDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(tenantuserview.Table, sqlgraph.NewFieldSpec(tenantuserview.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TenantUserViewDeleteOne is the builder for deleting a single TenantUserView entity.
type TenantUserViewDeleteOne struct {
	_d *TenantUserViewDelete
}

// Where appends a list predicates to the TenantUserViewDelete builder.
func (_d *TenantUserViewDeleteOne) Where(ps ...predicate.TenantUserView) *TenantUserViewDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TenantUserViewDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{tenantuserview.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TenantUserViewDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
