// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"good-todo-go/internal/ent/tenantuserview"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TenantUserViewCreate is the builder for creating a TenantUserView entity.
type TenantUserViewCreate struct {
	config
	mutation *TenantUserViewMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (_c *TenantUserViewCreate) SetTenantID(v string) *TenantUserViewCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetTenantName sets the "tenant_name" field.
func (_c *TenantUserViewCreate) SetTenantName(v string) *TenantUserViewCreate {
	_c.mutation.SetTenantName(v)
	return _c
}

// SetTenantSlug sets the "tenant_slug" field.
func (_c *TenantUserViewCreate) SetTenantSlug(v string) *TenantUserViewCreate {
	_c.mutation.SetTenantSlug(v)
	return _c
}

// SetEmail sets the "email" field.
func (_c *TenantUserViewCreate) SetEmail(v string) *TenantUserViewCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetName sets the "name" field.
func (_c *TenantUserViewCreate) SetName(v string) *TenantUserViewCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetRole sets the "role" field.
func (_c *TenantUserViewCreate) SetRole(v string) *TenantUserViewCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetEmailVerified sets the "email_verified" field.
func (_c *TenantUserViewCreate) SetEmailVerified(v bool) *TenantUserViewCreate {
	_c.mutation.SetEmailVerified(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TenantUserViewCreate) SetCreatedAt(v time.Time) *TenantUserViewCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TenantUserViewCreate) SetNillableCreatedAt(v *time.Time) *TenantUserViewCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TenantUserViewCreate) SetUpdatedAt(v time.Time) *TenantUserViewCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TenantUserViewCreate) SetNillableUpdatedAt(v *time.Time) *TenantUserViewCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TenantUserViewCreate) SetID(v string) *TenantUserViewCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the TenantUserViewMutation object of the builder.
func (_c *TenantUserViewCreate) Mutation() *TenantUserViewMutation {
	return _c.mutation
}

// Save creates the TenantUserView in the database.
func (_c *TenantUserViewCreate) Save(ctx context.Context) (*TenantUserView, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TenantUserViewCreate) SaveX(ctx context.Context) *TenantUserView {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TenantUserViewCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TenantUserViewCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TenantUserViewCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := tenantuserview.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := tenantuserview.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TenantUserViewCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "TenantUserView.tenant_id"`)}
	}
	if _, ok := _c.mutation.TenantName(); !ok {
		return &ValidationError{Name: "tenant_name", err: errors.New(`ent: missing required field "TenantUserView.tenant_name"`)}
	}
	if _, ok := _c.mutation.TenantSlug(); !ok {
		return &ValidationError{Name: "tenant_slug", err: errors.New(`ent: missing required field "TenantUserView.tenant_slug"`)}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "TenantUserView.email"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "TenantUserView.name"`)}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "TenantUserView.role"`)}
	}
	if _, ok := _c.mutation.EmailVerified(); !ok {
		return &ValidationError{Name: "email_verified", err: errors.New(`ent: missing required field "TenantUserView.email_verified"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TenantUserView.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TenantUserView.updated_at"`)}
	}
	return nil
}

func (_c *TenantUserViewCreate) sqlSave(ctx context.Context) (*TenantUserView, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected TenantUserView.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TenantUserViewCreate) createSpec() (*TenantUserView, *sqlgraph.CreateSpec) {
	var (
		_node = &TenantUserView{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tenantuserview.Table, sqlgraph.NewFieldSpec(tenantuserview.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(tenantuserview.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.TenantName(); ok {
		_spec.SetField(tenantuserview.FieldTenantName, field.TypeString, value)
		_node.TenantName = value
	}
	if value, ok := _c.mutation.TenantSlug(); ok {
		_spec.SetField(tenantuserview.FieldTenantSlug, field.TypeString, value)
		_node.TenantSlug = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(tenantuserview.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(tenantuserview.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(tenantuserview.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.EmailVerified(); ok {
		_spec.SetField(tenantuserview.FieldEmailVerified, field.TypeBool, value)
		_node.EmailVerified = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(tenantuserview.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(tenantuserview.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// TenantUserViewCreateBulk is the builder for creating many TenantUserView entities in bulk.
type TenantUserViewCreateBulk struct {
	config
	err      error
	builders []*TenantUserViewCreate
}

// Save creates the TenantUserView entities in the database.
func (_c *TenantUserViewCreateBulk) Save(ctx context.Context) ([]*TenantUserView, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TenantUserView, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TenantUserViewMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TenantUserViewCreateBulk) SaveX(ctx context.Context) []*TenantUserView {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TenantUserViewCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TenantUserViewCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
