// Code generated by MockGen. DO NOT EDIT.
// Source: auth.go
//
// Generated by this command:
//
//	mockgen -source=auth.go -destination=mock/auth.go -package=mock_repository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	model "good-todo-go/internal/domain/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIAuthRepository is a mock of IAuthRepository interface.
type MockIAuthRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIAuthRepositoryMockRecorder
	isgomock struct{}
}

// MockIAuthRepositoryMockRecorder is the mock recorder for MockIAuthRepository.
type MockIAuthRepositoryMockRecorder struct {
	mock *MockIAuthRepository
}

// NewMockIAuthRepository creates a new mock instance.
func NewMockIAuthRepository(ctrl *gomock.Controller) *MockIAuthRepository {
	mock := &MockIAuthRepository{ctrl: ctrl}
	mock.recorder = &MockIAuthRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAuthRepository) EXPECT() *MockIAuthRepositoryMockRecorder {
	return m.recorder
}

// CreateTenant mocks base method.
func (m *MockIAuthRepository) CreateTenant(ctx context.Context, tenant *model.Tenant) (*model.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTenant", ctx, tenant)
	ret0, _ := ret[0].(*model.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTenant indicates an expected call of CreateTenant.
func (mr *MockIAuthRepositoryMockRecorder) CreateTenant(ctx, tenant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTenant", reflect.TypeOf((*MockIAuthRepository)(nil).CreateTenant), ctx, tenant)
}

// CreateUser mocks base method.
func (m *MockIAuthRepository) CreateUser(ctx context.Context, user *model.User) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockIAuthRepositoryMockRecorder) CreateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockIAuthRepository)(nil).CreateUser), ctx, user)
}

// FindTenantBySlug mocks base method.
func (m *MockIAuthRepository) FindTenantBySlug(ctx context.Context, slug string) (*model.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTenantBySlug", ctx, slug)
	ret0, _ := ret[0].(*model.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTenantBySlug indicates an expected call of FindTenantBySlug.
func (mr *MockIAuthRepositoryMockRecorder) FindTenantBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTenantBySlug", reflect.TypeOf((*MockIAuthRepository)(nil).FindTenantBySlug), ctx, slug)
}

// FindUserByEmail mocks base method.
func (m *MockIAuthRepository) FindUserByEmail(ctx context.Context, tenantID, email string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByEmail", ctx, tenantID, email)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByEmail indicates an expected call of FindUserByEmail.
func (mr *MockIAuthRepositoryMockRecorder) FindUserByEmail(ctx, tenantID, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByEmail", reflect.TypeOf((*MockIAuthRepository)(nil).FindUserByEmail), ctx, tenantID, email)
}

// FindUserByID mocks base method.
func (m *MockIAuthRepository) FindUserByID(ctx context.Context, tenantID, userID string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByID", ctx, tenantID, userID)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByID indicates an expected call of FindUserByID.
func (mr *MockIAuthRepositoryMockRecorder) FindUserByID(ctx, tenantID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByID", reflect.TypeOf((*MockIAuthRepository)(nil).FindUserByID), ctx, tenantID, userID)
}

// FindUserByVerificationToken mocks base method.
func (m *MockIAuthRepository) FindUserByVerificationToken(ctx context.Context, token string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByVerificationToken", ctx, token)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByVerificationToken indicates an expected call of FindUserByVerificationToken.
func (mr *MockIAuthRepositoryMockRecorder) FindUserByVerificationToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByVerificationToken", reflect.TypeOf((*MockIAuthRepository)(nil).FindUserByVerificationToken), ctx, token)
}

// UpdateUser mocks base method.
func (m *MockIAuthRepository) UpdateUser(ctx context.Context, user *model.User) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, user)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockIAuthRepositoryMockRecorder) UpdateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockIAuthRepository)(nil).UpdateUser), ctx, user)
}
